### ISSUE TITLE
fistbump chrome extension error

### ISSUE THREAD

**Issue by pkrasam** [HandshakeAlliance/fistbump#4]
Just tried this to run the chrome extension pointing to handshake mainnet and seeing the following errors...

<img width="615" alt="fistbump-chrome-ext" src="https://user-images.githubusercontent.com/4514654/74643672-394f5c00-51c9-11ea-8695-f3b7290b97aa.png">

<img width="654" alt="fistbump-error" src="https://user-images.githubusercontent.com/4514654/74643686-3eaca680-51c9-11ea-8d89-6805f647e9dc.png">

**Comment by blockdylanb** [comment]
@pkrasam there's in a completely rewritten version of fistbump that I just pushed to master last night. Try pulling the latest and this issue should be gone.
